language: cpp

os:
  - linux

compiler:
  - gcc

install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:beineri/opt-qt55
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 libc6-i386 qt55base qt55declarative qt55quick1 qt55script qt55tools
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

script:
  - mkdir build && cd build
  - ruby ../qmake/configure.rb --prefix install --utest --examples
  - /opt/qt55/bin/qmake -r "QMAKE_CXX=g++-4.8" ../qmake/fougtools.pro
  - make -j4
